[phases.setup]
nixPkgs = [
  "nodejs-18_x",
  "npm-9_x",
  "openssl"
]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npx prisma generate",
  "npx prisma migrate",
  "npm run build"
]

[start]
cmd = "npm run start"