export const BOT_USERNAME = process.env.NEXT_PUBLIC_BOT_USERNAME!
export const BOT_TOKEN = process.env.NEXT_PUBLIC_BOT_TOKEN!

export const FUTUREVERSE_ENVIRONMENT = process.env.NEXT_PUBLIC_FUTUREVERSE_ENVIRONMENT!;
export const FUTUREVERSE_CLIENT_ID = process.env.NEXT_PUBLIC_FUTUREVERSE_CLIENT_ID!;
export const FUTUREVERSE_REDIRECT_URI = process.env.NEXT_PUBLIC_FUTUREVERSE_REDIRECT_URI!;

export const WALLET_CONNECT_PROJECT_ID = '068808367940b9806150ffeb8f1970e2';