export const WALLET_CONNECT_PROJECT_ID = '068808367940b9806150ffeb8f1970e2';

export const DATABASE_URL = process.env.NEXT_PUBLIC_DATABASE_URL!;

export const BOT_USERNAME = process.env.NEXT_PUBLIC_BOT_USERNAME!
export const BOT_TOKEN = process.env.NEXT_PUBLIC_BOT_TOKEN!

export const FUTUREVERSE_ENVIRONMENT = process.env.NEXT_PUBLIC_FUTUREVERSE_ENVIRONMENT!;
export const FUTUREVERSE_CLIENT_ID = process.env.NEXT_PUBLIC_FUTUREVERSE_CLIENT_ID!;
export const FUTUREVERSE_REDIRECT_URI = process.env.NEXT_PUBLIC_FUTUREVERSE_REDIRECT_URI!;
export const PUBLIC_NETWORK = process.env.NEXT_PUBLIC_NETWORK!;

export const APPWRITE_PROJECT_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID!;
export const APPWRITE_ENDPOINT = process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT!;
export const APPWRITE_KEY = process.env.NEXT_PUBLIC_APPWRITE_KEY!;
export const FUNCTION_ID = process.env.NEXT_PUBLIC_FUNCTION_ID!;
export const DATABASE_ID = process.env.NEXT_PUBLIC_DATABASE_ID!;
export const USER_COL_ID = process.env.NEXT_PUBLIC_USER_COL_ID!;
export const INVENTORY_COL_ID = process.env.NEXT_PUBLIC_INVENTORY_COL_ID!;

export const WORKER_URL = process.env.NEXT_PUBLIC_WORKER_URL!;
